# Training data for all IPC sections

ALL_IPC_TRAINING_DATA = [
    ("Someone stole my wallet", ['379']),
    ("My neighbor threatened to kill me", ['506']),
    ("I was assaulted by a group of people", ['323', '34']),
    ("What is IPC section 302?", ['302']),
    ("Tell me about IPC section 302 - Punishment for murder", ['302']),
    ("The accused committed for and life and shall against the victim", ['302']),
    ("The accused violated section 302 by whoever commits murder shall be punished with death, or imprisonment for life, and shall also be lia...", ['302']),
    ("The complainant reported that the accused committed an offense involving for and life", ['302']),
    ("What is IPC section 304B?", ['304B']),
    ("Tell me about IPC section 304B - Dowry death", ['304B']),
    ("The accused committed occurs and dowry and burns against the victim", ['304B']),
    ("The accused violated section 304B by where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under no...", ['304B']),
    ("The complainant reported that the accused committed an offense involving occurs and dowry", ['304B']),
    ("What is IPC section 354?", ['354']),
    ("Tell me about IPC section 354 - Assault or criminal force to woman with intent to outrage her modesty", ['354']),
    ("The accused committed modesty and force and knowing against the victim", ['354']),
    ("The accused violated section 354 by whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likel...", ['354']),
    ("The complainant reported that the accused committed an offense involving modesty and force", ['354']),
    ("What is IPC section 376?", ['376']),
    ("Tell me about IPC section 376 - Punishment for rape", ['376']),
    ("The accused committed for and description and term against the victim", ['376']),
    ("The accused violated section 376 by whoever commits rape shall be punished with imprisonment of either description for a term which shal...", ['376']),
    ("The complainant reported that the accused committed an offense involving for and description", ['376']),
    ("What is IPC section 420?", ['420']),
    ("Tell me about IPC section 420 - Cheating and dishonestly inducing delivery of property", ['420']),
    ("The accused committed thereby and of and dishonestly against the victim", ['420']),
    ("The accused violated section 420 by whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any pe...", ['420']),
    ("The complainant reported that the accused committed an offense involving thereby and of", ['420']),
    ("What is IPC section 498A?", ['498A']),
    ("Tell me about IPC section 498A - Husband or relative of husband of a woman subjecting her to cruelty", ['498A']),
    ("The accused committed subjecting and of and such against the victim", ['498A']),
    ("The accused violated section 498A by whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty...", ['498A']),
    ("The complainant reported that the accused committed an offense involving subjecting and of", ['498A']),
    ("What is IPC section 509?", ['509']),
    ("Tell me about IPC section 509 - Word, gesture or act intended to insult the modesty of a woman", ['509']),
    ("The accused committed modesty and intended and gesture against the victim", ['509']),
    ("The accused violated section 509 by whoever, intending to insult the modesty of any woman, utters any word, makes any sound or gesture, ...", ['509']),
    ("The complainant reported that the accused committed an offense involving modesty and intended", ['509']),
]
