"""
This type stub file was generated by pyright.
"""

def parse_version(v): # -> tuple[int, ...]:
    """
        Take a string version and conver it to a tuple (for easier comparison), e.g.:

            "1.2.3" --> (1, 2, 3)
            "1.2" --> (1, 2, 0)
            "1" --> (1, 0, 0)
    """
    ...

def sqlalchemy_version(op, val): # -> bool:
    ...

def engine_config_warning(config, version, deprecated_config_key, engine_option): # -> None:
    ...

