# Training data for IPC sections

TRAINING_DATA = [
    ("The accused murdered the victim by stabbing him multiple times.", ['302']),
    ("The victim was killed by the accused with a knife.", ['302']),
    ("The accused shot and killed the victim during an argument.", ['302']),
    ("The accused strangled the victim to death.", ['302']),
    ("The victim died due to poisoning administered by the accused.", ['302']),
    ("The accused hit the victim on the head with a heavy object causing death.", ['302']),
    ("The accused deliberately ran over the victim with a car, killing them instantly.", ['302']),
    ("The accused attempted to kill the victim by firing a gun.", ['307']),
    ("The accused tried to stab the victim but was stopped.", ['307']),
    ("The accused poisoned the food but the victim survived after hospital treatment.", ['307']),
    ("The accused pushed the victim from a height with intent to kill, but the victim survived.", ['307']),
    ("The accused attacked the victim with a deadly weapon but failed to kill them.", ['307']),
    ("The accused tried to strangle the victim but was interrupted.", ['307']),
    ("The accused assaulted the victim causing injuries.", ['323']),
    ("The accused slapped and punched the victim.", ['323']),
    ("The accused beat the victim with bare hands.", ['323']),
    ("The victim was physically assaulted by the accused.", ['323']),
    ("The accused pushed the victim causing them to fall and get injured.", ['323']),
    ("The accused sexually assaulted the victim.", ['376']),
    ("The accused raped the victim at his residence.", ['376']),
    ("The victim was sexually violated by the accused against her consent.", ['376']),
    ("The accused committed sexual intercourse with the victim without consent.", ['376']),
    ("The accused cheated the victim by selling fake property documents.", ['420']),
    ("The accused fraudulently took money promising a job that didn't exist.", ['420']),
    ("The victim was deceived into investing in a fake company by the accused.", ['420']),
    ("The accused sold counterfeit products claiming them to be genuine.", ['420']),
    ("The accused ran a Ponzi scheme defrauding multiple victims.", ['420']),
    ("The accused was charged with committing an offense against under section 1.", ['1']),
    ("The complainant reported that the accused committed an offense against, violating section 1.", ['1']),
    ("A case was filed against the accused for committing an offense against the victim under section 2.", ['2']),
    ("The victim alleged that the accused committed an offense against, which falls under section 2.", ['2']),
    ("The victim alleged that the accused committed an offense against, which falls under section 3.", ['3']),
    ("The accused committed an offense against the victim, which is an offense under section 3.", ['3']),
    ("The complainant reported that the accused committed an offense against, violating section 4.", ['4']),
    ("The accused was charged with committing an offense against under section 4.", ['4']),
    ("The victim alleged that the accused committed an offense against, which falls under section 5.", ['5']),
    ("A case was filed against the accused for committing an offense against the victim under section 5.", ['5']),
    ("The accused committed an offense against the victim, which is an offense under section 76.", ['76']),
    ("The victim alleged that the accused committed an offense against, which falls under section 76.", ['76']),
    ("The victim alleged that the accused committed an offense against, which falls under section 77.", ['77']),
    ("The accused was charged with committing an offense against under section 77.", ['77']),
    ("The accused committed an offense against the victim, which is an offense under section 78.", ['78']),
    ("The victim alleged that the accused committed an offense against, which falls under section 78.", ['78']),
    ("The accused was charged with committing an offense against under section 79.", ['79']),
    ("A case was filed against the accused for committing an offense against the victim under section 79.", ['79']),
    ("A case was filed against the accused for committing an offense against the victim under section 80.", ['80']),
    ("The complainant reported that the accused committed an offense against, violating section 80.", ['80']),
    ("A case was filed against the accused for committing an offense against the victim under section 81.", ['81']),
    ("The complainant reported that the accused committed an offense against, violating section 81.", ['81']),
    ("The victim alleged that the accused committed an offense against, which falls under section 82.", ['82']),
    ("A case was filed against the accused for committing an offense against the victim under section 82.", ['82']),
    ("The accused was charged with committing an offense against under section 83.", ['83']),
    ("The accused was charged with committing an offense against under section 83.", ['83']),
    ("The complainant reported that the accused committed an offense against, violating section 84.", ['84']),
    ("The complainant reported that the accused committed an offense against, violating section 84.", ['84']),
    ("A case was filed against the accused for committing an offense against the victim under section 85.", ['85']),
    ("A case was filed against the accused for committing an offense against the victim under section 85.", ['85']),
    ("The complainant reported that the accused committed an offense against, violating section 86.", ['86']),
    ("The accused was charged with committing an offense against under section 86.", ['86']),
    ("The accused assaulted the victim, which is an offense under section 87.", ['87']),
    ("The victim alleged that the accused assaulted, which falls under section 87.", ['87']),
    ("The victim alleged that the accused committed an offense against, which falls under section 88.", ['88']),
    ("The accused committed an offense against the victim, which is an offense under section 88.", ['88']),
    ("The accused was charged with committing an offense against under section 89.", ['89']),
    ("The accused committed an offense against the victim, which is an offense under section 89.", ['89']),
    ("The accused was charged with committing an offense against under section 90.", ['90']),
    ("The complainant reported that the accused committed an offense against, violating section 90.", ['90']),
    ("The accused committed an offense against the victim, which is an offense under section 91.", ['91']),
    ("The accused committed an offense against the victim, which is an offense under section 91.", ['91']),
    ("A case was filed against the accused for committing an offense against the victim under section 92.", ['92']),
    ("The accused committed an offense against the victim, which is an offense under section 92.", ['92']),
    ("The complainant reported that the accused committed an offense against, violating section 93.", ['93']),
    ("A case was filed against the accused for committing an offense against the victim under section 93.", ['93']),
    ("The complainant reported that the accused threatened, violating section 94.", ['94']),
    ("A case was filed against the accused for threatening the victim under section 94.", ['94']),
    ("The accused was charged with committing an offense against under section 95.", ['95']),
    ("The complainant reported that the accused committed an offense against, violating section 95.", ['95']),
    ("The accused was charged with committing an offense against under section 96.", ['96']),
    ("The accused was charged with committing an offense against under section 96.", ['96']),
    ("The accused was charged with committing an offense against under section 97.", ['97']),
    ("The accused was charged with committing an offense against under section 97.", ['97']),
    ("The accused committed an offense against the victim, which is an offense under section 98.", ['98']),
    ("The victim alleged that the accused committed an offense against, which falls under section 98.", ['98']),
    ("A case was filed against the accused for committing an offense against the victim under section 99.", ['99']),
    ("The accused was charged with committing an offense against under section 99.", ['99']),
    ("The complainant reported that the accused committed an offense against, violating section 100.", ['100']),
    ("A case was filed against the accused for committing an offense against the victim under section 100.", ['100']),
    ("The accused was charged with committing an offense against under section 101.", ['101']),
    ("A case was filed against the accused for committing an offense against the victim under section 101.", ['101']),
    ("The complainant reported that the accused committed an offense against, violating section 102.", ['102']),
    ("A case was filed against the accused for committing an offense against the victim under section 102.", ['102']),
    ("The accused committed an offense against the victim, which is an offense under section 103.", ['103']),
    ("The victim alleged that the accused committed an offense against, which falls under section 103.", ['103']),
    ("A case was filed against the accused for committing an offense against the victim under section 104.", ['104']),
    ("A case was filed against the accused for committing an offense against the victim under section 104.", ['104']),
    ("The complainant reported that the accused committed an offense against, violating section 105.", ['105']),
    ("The victim alleged that the accused committed an offense against, which falls under section 105.", ['105']),
    ("The accused assaulted the victim, which is an offense under section 106.", ['106']),
    ("The accused assaulted the victim, which is an offense under section 106.", ['106']),
    ("The complainant reported that the accused committed an offense against, violating section 107.", ['107']),
    ("The accused committed an offense against the victim, which is an offense under section 107.", ['107']),
    ("The complainant reported that the accused committed an offense against, violating section 108.", ['108']),
    ("A case was filed against the accused for committing an offense against the victim under section 108.", ['108']),
    ("The accused was charged with committing an offense against under section 109.", ['109']),
    ("The accused committed an offense against the victim, which is an offense under section 109.", ['109']),
    ("The accused was charged with committing an offense against under section 110.", ['110']),
    ("The complainant reported that the accused committed an offense against, violating section 110.", ['110']),
    ("A case was filed against the accused for committing an offense against the victim under section 111.", ['111']),
    ("The victim alleged that the accused committed an offense against, which falls under section 111.", ['111']),
    ("The complainant reported that the accused committed an offense against, violating section 112.", ['112']),
    ("A case was filed against the accused for committing an offense against the victim under section 112.", ['112']),
    ("A case was filed against the accused for committing an offense against the victim under section 113.", ['113']),
    ("The accused committed an offense against the victim, which is an offense under section 113.", ['113']),
    ("The complainant reported that the accused committed an offense against, violating section 114.", ['114']),
    ("The complainant reported that the accused committed an offense against, violating section 114.", ['114']),
    ("The complainant reported that the accused committed an offense against, violating section 115.", ['115']),
    ("The victim alleged that the accused committed an offense against, which falls under section 115.", ['115']),
    ("The accused was charged with committing an offense against under section 116.", ['116']),
    ("The accused committed an offense against the victim, which is an offense under section 116.", ['116']),
    ("The accused was charged with committing an offense against under section 117.", ['117']),
    ("The complainant reported that the accused committed an offense against, violating section 117.", ['117']),
    ("The complainant reported that the accused committed an offense against, violating section 118.", ['118']),
    ("The accused committed an offense against the victim, which is an offense under section 118.", ['118']),
    ("A case was filed against the accused for committing an offense against the victim under section 119.", ['119']),
    ("The complainant reported that the accused committed an offense against, violating section 119.", ['119']),
    ("The complainant reported that the accused committed an offense against, violating section 120.", ['120']),
    ("The accused committed an offense against the victim, which is an offense under section 120.", ['120']),
    ("The victim alleged that the accused committed an offense against, which falls under section 120A.", ['120A']),
    ("The complainant reported that the accused committed an offense against, violating section 120A.", ['120A']),
    ("The accused committed an offense against the victim, which is an offense under section 120B.", ['120B']),
    ("The accused committed an offense against the victim, which is an offense under section 120B.", ['120B']),
    ("The complainant reported that the accused committed an offense against, violating section 121.", ['121']),
    ("The complainant reported that the accused committed an offense against, violating section 121.", ['121']),
    ("The accused was charged with committing an offense against under section 121A.", ['121A']),
    ("The accused committed an offense against the victim, which is an offense under section 121A.", ['121A']),
    ("The accused committed an offense against the victim, which is an offense under section 122.", ['122']),
    ("The accused was charged with committing an offense against under section 122.", ['122']),
    ("A case was filed against the accused for committing an offense against the victim under section 123.", ['123']),
    ("A case was filed against the accused for committing an offense against the victim under section 123.", ['123']),
    ("The accused was charged with assaulting under section 124.", ['124']),
    ("The accused was charged with assaulting under section 124.", ['124']),
    ("A case was filed against the accused for committing an offense against the victim under section 124A.", ['124A']),
    ("A case was filed against the accused for committing an offense against the victim under section 124A.", ['124A']),
    ("The complainant reported that the accused committed an offense against, violating section 125.", ['125']),
    ("The victim alleged that the accused committed an offense against, which falls under section 125.", ['125']),
    ("A case was filed against the accused for committing an offense against the victim under section 126.", ['126']),
    ("The accused committed an offense against the victim, which is an offense under section 126.", ['126']),
    ("The victim alleged that the accused committed an offense against, which falls under section 127.", ['127']),
    ("The victim alleged that the accused committed an offense against, which falls under section 127.", ['127']),
    ("The accused committed an offense against the victim, which is an offense under section 128.", ['128']),
    ("The complainant reported that the accused committed an offense against, violating section 128.", ['128']),
    ("The victim alleged that the accused committed an offense against, which falls under section 129.", ['129']),
    ("A case was filed against the accused for committing an offense against the victim under section 129.", ['129']),
    ("The complainant reported that the accused committed an offense against, violating section 130.", ['130']),
    ("The victim alleged that the accused committed an offense against, which falls under section 130.", ['130']),
    ("The accused was charged with committing an offense against under section 141.", ['141']),
    ("A case was filed against the accused for committing an offense against the victim under section 141.", ['141']),
    ("A case was filed against the accused for committing an offense against the victim under section 142.", ['142']),
    ("The complainant reported that the accused committed an offense against, violating section 142.", ['142']),
    ("The accused was charged with committing an offense against under section 143.", ['143']),
    ("The victim alleged that the accused committed an offense against, which falls under section 143.", ['143']),
    ("The victim alleged that the accused committed an offense against, which falls under section 144.", ['144']),
    ("The accused was charged with committing an offense against under section 144.", ['144']),
    ("The accused was charged with committing an offense against under section 145.", ['145']),
    ("The complainant reported that the accused committed an offense against, violating section 145.", ['145']),
    ("A case was filed against the accused for committing an offense against the victim under section 146.", ['146']),
    ("A case was filed against the accused for committing an offense against the victim under section 146.", ['146']),
    ("The accused committed an offense against the victim, which is an offense under section 147.", ['147']),
    ("The complainant reported that the accused committed an offense against, violating section 147.", ['147']),
    ("The accused committed an offense against the victim, which is an offense under section 148.", ['148']),
    ("The complainant reported that the accused committed an offense against, violating section 148.", ['148']),
    ("The victim alleged that the accused committed an offense against, which falls under section 149.", ['149']),
    ("The accused committed an offense against the victim, which is an offense under section 149.", ['149']),
    ("A case was filed against the accused for committing an offense against the victim under section 150.", ['150']),
    ("The accused was charged with committing an offense against under section 150.", ['150']),
    ("The victim alleged that the accused committed an offense against, which falls under section 151.", ['151']),
    ("The victim alleged that the accused committed an offense against, which falls under section 151.", ['151']),
    ("The accused was charged with assaulting under section 152.", ['152']),
    ("A case was filed against the accused for assaulting the victim under section 152.", ['152']),
    ("The complainant reported that the accused committed an offense against, violating section 153.", ['153']),
    ("The victim alleged that the accused committed an offense against, which falls under section 153.", ['153']),
    ("The victim alleged that the accused committed an offense against, which falls under section 153A.", ['153A']),
    ("A case was filed against the accused for committing an offense against the victim under section 153A.", ['153A']),
    ("The accused committed an offense against the victim, which is an offense under section 153B.", ['153B']),
    ("A case was filed against the accused for committing an offense against the victim under section 153B.", ['153B']),
    ("The accused was charged with committing an offense against under section 154.", ['154']),
    ("The complainant reported that the accused committed an offense against, violating section 154.", ['154']),
    ("A case was filed against the accused for committing an offense against the victim under section 155.", ['155']),
    ("The victim alleged that the accused committed an offense against, which falls under section 155.", ['155']),
    ("The victim alleged that the accused committed an offense against, which falls under section 156.", ['156']),
    ("A case was filed against the accused for committing an offense against the victim under section 156.", ['156']),
    ("The victim alleged that the accused committed an offense against, which falls under section 157.", ['157']),
    ("The accused was charged with committing an offense against under section 157.", ['157']),
    ("The complainant reported that the accused committed an offense against, violating section 158.", ['158']),
    ("A case was filed against the accused for committing an offense against the victim under section 158.", ['158']),
    ("The accused was charged with committing an offense against under section 159.", ['159']),
    ("The accused was charged with committing an offense against under section 159.", ['159']),
    ("The accused committed an offense against the victim, which is an offense under section 160.", ['160']),
    ("The victim alleged that the accused committed an offense against, which falls under section 160.", ['160']),
    ("The accused was charged with assaulting under section 166.", ['166']),
    ("The accused assaulted the victim, which is an offense under section 166.", ['166']),
    ("The accused was charged with committing an offense against under section 166A.", ['166A']),
    ("A case was filed against the accused for committing an offense against the victim under section 166A.", ['166A']),
    ("The accused was charged with committing an offense against under section 166B.", ['166B']),
    ("The complainant reported that the accused committed an offense against, violating section 166B.", ['166B']),
    ("The victim alleged that the accused assaulted, which falls under section 167.", ['167']),
    ("A case was filed against the accused for assaulting the victim under section 167.", ['167']),
    ("The complainant reported that the accused committed an offense against, violating section 168.", ['168']),
    ("A case was filed against the accused for committing an offense against the victim under section 168.", ['168']),
    ("The complainant reported that the accused committed an offense against, violating section 169.", ['169']),
    ("The complainant reported that the accused committed an offense against, violating section 169.", ['169']),
    ("The accused was charged with committing an offense against under section 170.", ['170']),
    ("The accused committed an offense against the victim, which is an offense under section 170.", ['170']),
    ("A case was filed against the accused for defrauding the victim under section 171.", ['171']),
    ("The complainant reported that the accused defrauded, violating section 171.", ['171']),
    ("The accused killed the victim, which is an offense under section 299.", ['299']),
    ("The complainant reported that the accused killed, violating section 299.", ['299']),
    ("A case was filed against the accused for killing the victim under section 300.", ['300']),
    ("The victim alleged that the accused killed, which falls under section 300.", ['300']),
    ("The complainant reported that the accused killed, violating section 304.", ['304']),
    ("The complainant reported that the accused killed, violating section 304.", ['304']),
    ("The victim alleged that the accused committed an offense against, which falls under section 304A.", ['304A']),
    ("The accused was charged with committing an offense against under section 304A.", ['304A']),
    ("The accused was charged with committing an offense against under section 304B.", ['304B']),
    ("The accused committed an offense against the victim, which is an offense under section 304B.", ['304B']),
    ("A case was filed against the accused for committing an offense against the victim under section 305.", ['305']),
    ("The accused committed an offense against the victim, which is an offense under section 305.", ['305']),
    ("The complainant reported that the accused committed an offense against, violating section 306.", ['306']),
    ("A case was filed against the accused for committing an offense against the victim under section 306.", ['306']),
    ("A case was filed against the accused for killing the victim under section 308.", ['308']),
    ("The complainant reported that the accused killed, violating section 308.", ['308']),
    ("The complainant reported that the accused committed an offense against, violating section 309.", ['309']),
    ("The complainant reported that the accused committed an offense against, violating section 309.", ['309']),
    ("The victim alleged that the accused committed an offense against, which falls under section 312.", ['312']),
    ("The victim alleged that the accused committed an offense against, which falls under section 312.", ['312']),
    ("The victim alleged that the accused assaulted, which falls under section 319.", ['319']),
    ("The victim alleged that the accused assaulted, which falls under section 319.", ['319']),
    ("The accused assaulted the victim, which is an offense under section 320.", ['320']),
    ("The accused was charged with assaulting under section 320.", ['320']),
    ("The accused assaulted the victim, which is an offense under section 321.", ['321']),
    ("The accused assaulted the victim, which is an offense under section 321.", ['321']),
    ("The complainant reported that the accused assaulted, violating section 322.", ['322']),
    ("The accused was charged with assaulting under section 322.", ['322']),
    ("A case was filed against the accused for assaulting the victim under section 324.", ['324']),
    ("The accused assaulted the victim, which is an offense under section 324.", ['324']),
    ("The complainant reported that the accused assaulted, violating section 325.", ['325']),
    ("The complainant reported that the accused assaulted, violating section 325.", ['325']),
    ("The victim alleged that the accused assaulted, which falls under section 326.", ['326']),
    ("The accused was charged with assaulting under section 326.", ['326']),
    ("The complainant reported that the accused committed an offense against, violating section 326A.", ['326A']),
    ("The complainant reported that the accused committed an offense against, violating section 326A.", ['326A']),
    ("The victim alleged that the accused committed an offense against, which falls under section 326B.", ['326B']),
    ("The complainant reported that the accused committed an offense against, violating section 326B.", ['326B']),
    ("A case was filed against the accused for assaulting the victim under section 327.", ['327']),
    ("The accused was charged with assaulting under section 327.", ['327']),
    ("The victim alleged that the accused assaulted, which falls under section 328.", ['328']),
    ("The victim alleged that the accused assaulted, which falls under section 328.", ['328']),
    ("The victim alleged that the accused assaulted, which falls under section 329.", ['329']),
    ("The victim alleged that the accused assaulted, which falls under section 329.", ['329']),
    ("A case was filed against the accused for assaulting the victim under section 334.", ['334']),
    ("The victim alleged that the accused assaulted, which falls under section 334.", ['334']),
    ("The accused was charged with assaulting under section 335.", ['335']),
    ("The complainant reported that the accused assaulted, violating section 335.", ['335']),
    ("The accused committed an offense against the victim, which is an offense under section 336.", ['336']),
    ("The victim alleged that the accused committed an offense against, which falls under section 336.", ['336']),
    ("A case was filed against the accused for assaulting the victim under section 337.", ['337']),
    ("A case was filed against the accused for assaulting the victim under section 337.", ['337']),
    ("The accused was charged with assaulting under section 338.", ['338']),
    ("The victim alleged that the accused assaulted, which falls under section 338.", ['338']),
    ("The complainant reported that the accused committed an offense against, violating section 339.", ['339']),
    ("A case was filed against the accused for committing an offense against the victim under section 339.", ['339']),
    ("The complainant reported that the accused committed an offense against, violating section 340.", ['340']),
    ("The complainant reported that the accused committed an offense against, violating section 340.", ['340']),
    ("The accused committed an offense against the victim, which is an offense under section 341.", ['341']),
    ("The accused was charged with committing an offense against under section 341.", ['341']),
    ("A case was filed against the accused for committing an offense against the victim under section 342.", ['342']),
    ("The victim alleged that the accused committed an offense against, which falls under section 342.", ['342']),
    ("A case was filed against the accused for committing an offense against the victim under section 343.", ['343']),
    ("The victim alleged that the accused committed an offense against, which falls under section 343.", ['343']),
    ("The accused was charged with committing an offense against under section 344.", ['344']),
    ("The complainant reported that the accused committed an offense against, violating section 344.", ['344']),
    ("A case was filed against the accused for committing an offense against the victim under section 346.", ['346']),
    ("The accused was charged with committing an offense against under section 346.", ['346']),
    ("The complainant reported that the accused committed an offense against, violating section 350.", ['350']),
    ("The accused committed an offense against the victim, which is an offense under section 350.", ['350']),
    ("The complainant reported that the accused assaulted, violating section 351.", ['351']),
    ("The complainant reported that the accused assaulted, violating section 351.", ['351']),
    ("The complainant reported that the accused assaulted, violating section 352.", ['352']),
    ("The complainant reported that the accused assaulted, violating section 352.", ['352']),
    ("The accused assaulted the victim, which is an offense under section 354.", ['354']),
    ("The complainant reported that the accused assaulted, violating section 354.", ['354']),
    ("The accused was charged with sexually assaulting under section 354A.", ['354A']),
    ("The accused was charged with sexually assaulting under section 354A.", ['354A']),
    ("The accused assaulted the victim, which is an offense under section 354B.", ['354B']),
    ("The victim alleged that the accused assaulted, which falls under section 354B.", ['354B']),
    ("The accused was charged with committing an offense against under section 354C.", ['354C']),
    ("The victim alleged that the accused committed an offense against, which falls under section 354C.", ['354C']),
    ("The accused committed an offense against the victim, which is an offense under section 354D.", ['354D']),
    ("A case was filed against the accused for committing an offense against the victim under section 354D.", ['354D']),
    ("The victim alleged that the accused kidnapped, which falls under section 359.", ['359']),
    ("The complainant reported that the accused kidnapped, violating section 359.", ['359']),
    ("A case was filed against the accused for kidnapping the victim under section 363.", ['363']),
    ("A case was filed against the accused for kidnapping the victim under section 363.", ['363']),
    ("The complainant reported that the accused kidnapped, violating section 363A.", ['363A']),
    ("The accused was charged with kidnapping under section 363A.", ['363A']),
    ("A case was filed against the accused for kidnapping the victim under section 366.", ['366']),
    ("The victim alleged that the accused kidnapped, which falls under section 366.", ['366']),
    ("The accused committed an offense against the victim, which is an offense under section 366A.", ['366A']),
    ("The accused committed an offense against the victim, which is an offense under section 366A.", ['366A']),
    ("A case was filed against the accused for committing an offense against the victim under section 366B.", ['366B']),
    ("The accused committed an offense against the victim, which is an offense under section 366B.", ['366B']),
    ("The accused committed an offense against the victim, which is an offense under section 370.", ['370']),
    ("The victim alleged that the accused committed an offense against, which falls under section 370.", ['370']),
    ("A case was filed against the accused for committing an offense against the victim under section 370A.", ['370A']),
    ("The victim alleged that the accused committed an offense against, which falls under section 370A.", ['370A']),
    ("The victim alleged that the accused sexually assaulted, which falls under section 375.", ['375']),
    ("The complainant reported that the accused sexually assaulted, violating section 375.", ['375']),
    ("The accused was charged with committing an offense against under section 376A.", ['376A']),
    ("The victim alleged that the accused committed an offense against, which falls under section 376A.", ['376A']),
    ("A case was filed against the accused for sexually assaulting the victim under section 376B.", ['376B']),
    ("The accused sexually assaulted the victim, which is an offense under section 376B.", ['376B']),
    ("The victim alleged that the accused sexually assaulted, which falls under section 376C.", ['376C']),
    ("A case was filed against the accused for sexually assaulting the victim under section 376C.", ['376C']),
    ("The accused sexually assaulted the victim, which is an offense under section 376D.", ['376D']),
    ("The accused sexually assaulted the victim, which is an offense under section 376D.", ['376D']),
    ("A case was filed against the accused for committing an offense against the victim under section 376E.", ['376E']),
    ("A case was filed against the accused for committing an offense against the victim under section 376E.", ['376E']),
    ("The accused stole property from the victim, which is an offense under section 378.", ['378']),
    ("The complainant reported that the accused stole property from, violating section 378.", ['378']),
    ("The victim alleged that the accused stole property from, which falls under section 379.", ['379']),
    ("A case was filed against the accused for stealing property from the victim under section 379.", ['379']),
    ("The victim alleged that the accused stole property from, which falls under section 380.", ['380']),
    ("The complainant reported that the accused stole property from, violating section 380.", ['380']),
    ("The complainant reported that the accused stole property from, violating section 381.", ['381']),
    ("The accused stole property from the victim, which is an offense under section 381.", ['381']),
    ("The complainant reported that the accused assaulted, violating section 382.", ['382']),
    ("The victim alleged that the accused assaulted, which falls under section 382.", ['382']),
    ("The complainant reported that the accused committed an offense against, violating section 383.", ['383']),
    ("The accused was charged with committing an offense against under section 383.", ['383']),
    ("A case was filed against the accused for committing an offense against the victim under section 384.", ['384']),
    ("The complainant reported that the accused committed an offense against, violating section 384.", ['384']),
    ("The victim alleged that the accused assaulted, which falls under section 385.", ['385']),
    ("A case was filed against the accused for assaulting the victim under section 385.", ['385']),
    ("A case was filed against the accused for committing an offense against the victim under section 386.", ['386']),
    ("The complainant reported that the accused committed an offense against, violating section 386.", ['386']),
    ("The accused was charged with committing an offense against under section 387.", ['387']),
    ("The complainant reported that the accused committed an offense against, violating section 387.", ['387']),
    ("The complainant reported that the accused threatened, violating section 388.", ['388']),
    ("A case was filed against the accused for threatening the victim under section 388.", ['388']),
    ("The accused committed an offense against the victim, which is an offense under section 389.", ['389']),
    ("The accused was charged with committing an offense against under section 389.", ['389']),
    ("The accused committed an offense against the victim, which is an offense under section 390.", ['390']),
    ("The victim alleged that the accused committed an offense against, which falls under section 390.", ['390']),
    ("A case was filed against the accused for committing an offense against the victim under section 391.", ['391']),
    ("The accused committed an offense against the victim, which is an offense under section 391.", ['391']),
    ("The accused was charged with committing an offense against under section 392.", ['392']),
    ("The complainant reported that the accused committed an offense against, violating section 392.", ['392']),
    ("The complainant reported that the accused committed an offense against, violating section 393.", ['393']),
    ("The accused was charged with committing an offense against under section 393.", ['393']),
    ("The complainant reported that the accused assaulted, violating section 394.", ['394']),
    ("The accused assaulted the victim, which is an offense under section 394.", ['394']),
    ("A case was filed against the accused for committing an offense against the victim under section 395.", ['395']),
    ("A case was filed against the accused for committing an offense against the victim under section 395.", ['395']),
    ("The complainant reported that the accused killed, violating section 396.", ['396']),
    ("The accused killed the victim, which is an offense under section 396.", ['396']),
    ("A case was filed against the accused for committing an offense against the victim under section 397.", ['397']),
    ("The accused committed an offense against the victim, which is an offense under section 397.", ['397']),
    ("The accused was charged with committing an offense against under section 398.", ['398']),
    ("The accused committed an offense against the victim, which is an offense under section 398.", ['398']),
    ("The victim alleged that the accused committed an offense against, which falls under section 399.", ['399']),
    ("The accused committed an offense against the victim, which is an offense under section 399.", ['399']),
    ("The accused committed an offense against the victim, which is an offense under section 402.", ['402']),
    ("The accused committed an offense against the victim, which is an offense under section 402.", ['402']),
    ("The victim alleged that the accused committed an offense against, which falls under section 403.", ['403']),
    ("The accused committed an offense against the victim, which is an offense under section 403.", ['403']),
    ("A case was filed against the accused for committing an offense against the victim under section 404.", ['404']),
    ("The victim alleged that the accused committed an offense against, which falls under section 404.", ['404']),
    ("The accused committed an offense against the victim, which is an offense under section 405.", ['405']),
    ("The victim alleged that the accused committed an offense against, which falls under section 405.", ['405']),
    ("The accused was charged with committing an offense against under section 406.", ['406']),
    ("A case was filed against the accused for committing an offense against the victim under section 406.", ['406']),
    ("A case was filed against the accused for committing an offense against the victim under section 407.", ['407']),
    ("The complainant reported that the accused committed an offense against, violating section 407.", ['407']),
    ("The accused was charged with committing an offense against under section 408.", ['408']),
    ("The victim alleged that the accused committed an offense against, which falls under section 408.", ['408']),
    ("The accused committed an offense against the victim, which is an offense under section 409.", ['409']),
    ("The victim alleged that the accused committed an offense against, which falls under section 409.", ['409']),
    ("A case was filed against the accused for committing an offense against the victim under section 410.", ['410']),
    ("The complainant reported that the accused committed an offense against, violating section 410.", ['410']),
    ("The accused committed an offense against the victim, which is an offense under section 411.", ['411']),
    ("A case was filed against the accused for committing an offense against the victim under section 411.", ['411']),
    ("The victim alleged that the accused committed an offense against, which falls under section 412.", ['412']),
    ("The complainant reported that the accused committed an offense against, violating section 412.", ['412']),
    ("The complainant reported that the accused committed an offense against, violating section 413.", ['413']),
    ("The accused committed an offense against the victim, which is an offense under section 413.", ['413']),
    ("The accused was charged with committing an offense against under section 414.", ['414']),
    ("The accused committed an offense against the victim, which is an offense under section 414.", ['414']),
    ("The accused was charged with defrauding under section 415.", ['415']),
    ("The accused defrauded the victim, which is an offense under section 415.", ['415']),
    ("The accused was charged with defrauding under section 416.", ['416']),
    ("A case was filed against the accused for defrauding the victim under section 416.", ['416']),
    ("The victim alleged that the accused defrauded, which falls under section 417.", ['417']),
    ("The accused was charged with defrauding under section 417.", ['417']),
    ("A case was filed against the accused for defrauding the victim under section 418.", ['418']),
    ("The complainant reported that the accused defrauded, violating section 418.", ['418']),
    ("The accused defrauded the victim, which is an offense under section 419.", ['419']),
    ("A case was filed against the accused for defrauding the victim under section 419.", ['419']),
    ("The victim alleged that the accused defrauded, which falls under section 421.", ['421']),
    ("The accused defrauded the victim, which is an offense under section 421.", ['421']),
    ("The victim alleged that the accused defrauded, which falls under section 422.", ['422']),
    ("The victim alleged that the accused defrauded, which falls under section 422.", ['422']),
    ("The accused defrauded the victim, which is an offense under section 423.", ['423']),
    ("A case was filed against the accused for defrauding the victim under section 423.", ['423']),
    ("The accused defrauded the victim, which is an offense under section 424.", ['424']),
    ("The accused was charged with defrauding under section 424.", ['424']),
    ("The victim alleged that the accused committed an offense against, which falls under section 425.", ['425']),
    ("The complainant reported that the accused committed an offense against, violating section 425.", ['425']),
    ("The accused committed an offense against the victim, which is an offense under section 426.", ['426']),
    ("The complainant reported that the accused committed an offense against, violating section 426.", ['426']),
    ("The complainant reported that the accused committed an offense against, violating section 427.", ['427']),
    ("The accused committed an offense against the victim, which is an offense under section 427.", ['427']),
    ("The accused was charged with killing under section 428.", ['428']),
    ("The accused killed the victim, which is an offense under section 428.", ['428']),
    ("The accused was charged with killing under section 429.", ['429']),
    ("A case was filed against the accused for killing the victim under section 429.", ['429']),
    ("The accused assaulted the victim, which is an offense under section 430.", ['430']),
    ("The accused assaulted the victim, which is an offense under section 430.", ['430']),
    ("The accused was charged with assaulting under section 431.", ['431']),
    ("The complainant reported that the accused assaulted, violating section 431.", ['431']),
    ("The complainant reported that the accused committed an offense against, violating section 434.", ['434']),
    ("The complainant reported that the accused committed an offense against, violating section 434.", ['434']),
    ("The accused committed an offense against the victim, which is an offense under section 435.", ['435']),
    ("A case was filed against the accused for committing an offense against the victim under section 435.", ['435']),
    ("The accused was charged with committing an offense against under section 436.", ['436']),
    ("The accused committed an offense against the victim, which is an offense under section 436.", ['436']),
    ("The accused was charged with committing an offense against under section 437.", ['437']),
    ("The complainant reported that the accused committed an offense against, violating section 437.", ['437']),
    ("The accused committed an offense against the victim, which is an offense under section 438.", ['438']),
    ("The victim alleged that the accused committed an offense against, which falls under section 438.", ['438']),
    ("The accused committed an offense against the victim, which is an offense under section 439.", ['439']),
    ("The victim alleged that the accused committed an offense against, which falls under section 439.", ['439']),
    ("The accused committed an offense against the victim, which is an offense under section 440.", ['440']),
    ("The victim alleged that the accused committed an offense against, which falls under section 440.", ['440']),
    ("The accused was charged with trespassing on the property of under section 447.", ['447']),
    ("The accused was charged with trespassing on the property of under section 447.", ['447']),
    ("A case was filed against the accused for trespassing on the property of the victim under section 448.", ['448']),
    ("A case was filed against the accused for trespassing on the property of the victim under section 448.", ['448']),
    ("The accused trespassed on the property of the victim, which is an offense under section 449.", ['449']),
    ("The victim alleged that the accused trespassed on the property of, which falls under section 449.", ['449']),
    ("The complainant reported that the accused trespassed on the property of, violating section 450.", ['450']),
    ("The complainant reported that the accused trespassed on the property of, violating section 450.", ['450']),
    ("A case was filed against the accused for trespassing on the property of the victim under section 451.", ['451']),
    ("The accused trespassed on the property of the victim, which is an offense under section 451.", ['451']),
    ("The victim alleged that the accused assaulted, which falls under section 452.", ['452']),
    ("The victim alleged that the accused assaulted, which falls under section 452.", ['452']),
    ("The accused trespassed on the property of the victim, which is an offense under section 453.", ['453']),
    ("The complainant reported that the accused trespassed on the property of, violating section 453.", ['453']),
    ("The victim alleged that the accused trespassed on the property of, which falls under section 454.", ['454']),
    ("The victim alleged that the accused trespassed on the property of, which falls under section 454.", ['454']),
    ("The accused was charged with assaulting under section 455.", ['455']),
    ("The accused assaulted the victim, which is an offense under section 455.", ['455']),
    ("The accused trespassed on the property of the victim, which is an offense under section 456.", ['456']),
    ("A case was filed against the accused for trespassing on the property of the victim under section 456.", ['456']),
    ("A case was filed against the accused for trespassing on the property of the victim under section 457.", ['457']),
    ("The accused trespassed on the property of the victim, which is an offense under section 457.", ['457']),
    ("The accused was charged with assaulting under section 458.", ['458']),
    ("The accused assaulted the victim, which is an offense under section 458.", ['458']),
    ("The accused was charged with assaulting under section 459.", ['459']),
    ("The accused was charged with assaulting under section 459.", ['459']),
    ("The accused was charged with assaulting under section 460.", ['460']),
    ("The accused assaulted the victim, which is an offense under section 460.", ['460']),
    ("A case was filed against the accused for committing an offense against the victim under section 498A.", ['498A']),
    ("A case was filed against the accused for committing an offense against the victim under section 498A.", ['498A']),
    ("The accused defamed the victim, which is an offense under section 499.", ['499']),
    ("The accused was charged with defaming under section 499.", ['499']),
    ("The victim alleged that the accused defamed, which falls under section 500.", ['500']),
    ("A case was filed against the accused for defaming the victim under section 500.", ['500']),
    ("The victim alleged that the accused threatened, which falls under section 503.", ['503']),
    ("The accused threatened the victim, which is an offense under section 503.", ['503']),
    ("A case was filed against the accused for defaming the victim under section 504.", ['504']),
    ("The accused defamed the victim, which is an offense under section 504.", ['504']),
    ("The accused was charged with committing an offense against under section 505.", ['505']),
    ("The accused committed an offense against the victim, which is an offense under section 505.", ['505']),
    ("The victim alleged that the accused threatened, which falls under section 506.", ['506']),
    ("The accused was charged with threatening under section 506.", ['506']),
    ("The accused was charged with threatening under section 507.", ['507']),
    ("The victim alleged that the accused threatened, which falls under section 507.", ['507']),
    ("The accused was charged with committing an offense against under section 508.", ['508']),
    ("The complainant reported that the accused committed an offense against, violating section 508.", ['508']),
    ("The accused defamed the victim, which is an offense under section 509.", ['509']),
    ("The complainant reported that the accused defamed, violating section 509.", ['509']),
    ("The accused was charged with committing an offense against under section 510.", ['510']),
    ("The accused committed an offense against the victim, which is an offense under section 510.", ['510']),
]
